name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [7.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
#      - run: npm install npm@5
      - run: npm install
#      - run: npm ci
      - run: npm run build
      - run: ls -al dest/
#      - run: npm test
